### ISSUE TITLE
[Suggestion] Since all of the git-* commands are broken, why not use the pending/git- tools that `toybox` provides?

### ISSUE THREAD

**Issue by xplshn** [Azathothas/Toolpacks#14]
Since all of the git-* commands are broken, why not use the pending/git- tools that `toybox` provides? Toybox can compile toy's as independent tools, so, it is feasible and a much better alternative than providing binaries that don't work at all.

**Comment by Azathothas** [comment]
[pending/git](https://github.com/landley/toybox/blob/master/toys/pending/git.c) seems to be a very, very limited implementation. I might consider it if it was already in stable build.

There's already much better & mature alternatives (tested in a minimal alpine):
- [Jujutsu](https://github.com/martinvonz/jj/blob/main/docs/git-comparison.md)
```bash
❯ jj git clone [OPTIONS] <SOURCE> [DESTINATION]
❯ jj git clone --quiet "https://github.com/Azathothas/Toolpacks"
```
- [gitoxide](https://github.com/Byron/gitoxide/blob/main/crate-status.md#gix)
```bash
❯ gix clone "https://github.com/Azathothas/Toolpacks"
```
- [go-git](https://github.com/go-git/go-git/tree/master/_examples)
```bash
❯ git-clone <url> <directory>
❯ git-clone https://github.com/Azathothas/Toolpacks Toolpacks
```

All of these are already part of the build scripts and included in [Toolpacks](https://bin.ajam.dev)

**Comment by xplshn** [comment]
Okay. I knew Gix, its great, I use it a loot.
