### ISSUE TITLE
[Broken] Remove Wezterm from the repos (wezterm-gui is missing, thus it cannot be used)

### ISSUE THREAD

**Issue by xplshn** [Azathothas/Toolpacks#19]
If the goal is to add graphical packages, we could start with something simpler like ST (simple Terminal by suckless.org), or maybe some small window managers like CWM, Fluxbox, Sway (not so small, but some distros compile it statically), maybe even Dillo (the no-JS browser!), or some of the https://www.enlightenment.org programs like Terminology.

**Comment by Azathothas** [comment]
wezterm can be run on two different machines, the server (statically compiled) on a remote cloud machine, and the gui (client) (downloadable from elsewhere) on your main pc/workstation.
see: 
- https://wezfurlong.org/wezterm/multiplexing.html
- https://github.com/wez/wezterm/discussions/3901
- https://github.com/wez/wezterm/issues/3385

> If the goal is to add graphical packages

It is not.

**Comment by xplshn** [comment]
understood, I wasn't familiar with that use-case for Wezterm. I've always used Screen or TMUX
