### ISSUE TITLE
aarch64 linux wget compiled without c-ares, can't use c-ares related options

### ISSUE THREAD

**Issue by wulungnet** [Azathothas/Toolpacks#23]
Using some of your compiled app on my phone with 'Terminal Emulator' app. I use linux aarch64 version.
When I use wget, I can't use some feature that linked to c-ares. Can you add this to your next compile batch ?
Thanks.

**Comment by Azathothas** [comment]
May I ask why do you not use the [`arm64-v8a Android`](https://bin.ajam.dev/arm64_v8a_Android/wget) version?
The wget binary for  [`arm64-v8a Android`](https://github.com/Azathothas/Toolpacks/blob/main/.github/scripts/arm64_v8a_Android/bins/wget.sh) is specifically compiled using [`ndk-pkg`](https://github.com/leleliu008/ndk-pkg-formula-repository-official-core/blob/master/formula/wget.yml) to work with Android, as long as you:
```bash
 pass --dns-servers=<DNS-SERVERS> argument to curl like below
 wget --dns-servers=8.8.8.8 https://example.com
```

Compiling without c-ares will disable lots of features which will render most of wget's function useless.

**Comment by wulungnet** [comment]
The aarch64 linux version of wget already compiled without c-ares, indicated there '-cares' on the show version command.
![IMG_20240701_183928](https://github.com/Azathothas/Toolpacks/assets/26988491/febc9f05-5a8a-4d88-bec5-84c986293d12)


The arm64-v8 cannot run under shell on 'Terminal Emulator' app, complaining 'cannot locate symbol : fread_unlocked ' then aborting.
![IMG_20240701_185104](https://github.com/Azathothas/Toolpacks/assets/26988491/532d3151-34cc-42a8-9870-8117377f41c7)

**Comment by Azathothas** [comment]
Oh! I see.

The Linux aarch64 version is compiled using nix, I didn't know it disabled c-ares.

I tested the android binary under a Termux shell which didn't error out like in your screenshots, hence passing the checks and getting pushed to the bucket.

I will take a look at this again tmr, and test using both [Termux](https://f-droid.org/en/packages/com.termux/) & [Terminal Emulator](https://f-droid.org/en/packages/com.termoneplus/)
Though last time I compiled wget statically for android, lots of things broke.

**Comment by wulungnet** [comment]
What work for me is using gocurl (can define dns and ssl/tls version) but it doesn't support -J -O so had to add -o filename option.
Note : previously I use userLAnd but its broken now. I can't use termux and other full linux emulator now, my phone need upgrade, didn't have much space left, hence I use Terminal Emulator.
Xiaomi Redmi Note 5 with Android 8.1.0, so API Level 27 maybe.

**Comment by Azathothas** [comment]
My android binaries target a minimum of API level 29 ( Android 10) and that's why you got the `cannot locate symbol : fread_unlocked` error

I have recompiled two versions of wget, one dynamic targeting 25 (Android 7.1) & another completely static which should work as long as you specify `--dns-servers` & `--ca-certificate`

- https://bin.ajam.dev/arm64_v8a_Android/wget_dynamic_api_25
- https://bin.ajam.dev/arm64_v8a_Android/wget_static


- cert: https://bin.ajam.dev/arm64_v8a_Android/wget_cacert.pem
> ```bash
> !# Either specify directly 
> --ca-certificate="$PATH_TO/cacert.pem"
>
> !# Or use an env Variable
> export SSL_CERT_FILE="$PATH_TO/cacert.pem"
>
> !# Or Define in wgetrc
> https://www.gnu.org/software/wget/manual/html_node/Sample-Wgetrc.html
> ```

- File Metadata
> ```bash
> #This will work, up from > API Level 25 (Android 7.1), and you don't need to use --dns-servers="8.8.8.8"
> wget_dynamic_api_25: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
> +cares +digest -gpgme +https +ipv6 +iri +large-file -metalink -nls
> +ntlm +opie -psl +ssl/openssl
> 
> 
> #This will work on any API, but you will need to use --dns-servers="8.8.8.8"
> wget_static:         ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
> +cares +digest -gpgme +https +ipv6 +iri +large-file -metalink -nls
> +ntlm +opie -psl +ssl/openssl
> 
> ```

**Comment by wulungnet** [comment]
Thanks. Still at work. I'll try it later.
I'll reopen if problem came up.

**Comment by wulungnet** [comment]
> 
> * https://bin.ajam.dev/arm64_v8a_Android/wget_dynamic_api_25
> * https://bin.ajam.dev/arm64_v8a_Android/wget_static
> 

sorry, got 404 file not found error.

**Comment by Azathothas** [comment]
Does the default wget (dynamic) at https://bin.ajam.dev/arm64_v8a_Android/wget not work?

**Comment by wulungnet** [comment]
can't download the files from your server. might be permission problem. 404 object not found.

**Comment by Azathothas** [comment]
> can't download the files from your server. might be permission problem. 404 object not found.

That's expected for

        https://bin.ajam.dev/arm64_v8a_Android/wget_dynamic_api_25
        https://bin.ajam.dev/arm64_v8a_Android/wget_static
Since I deleted them

I meant, try the https://bin.ajam.dev/arm64_v8a_Android/wget , it should work
