### ISSUE TITLE
[ BIN REQUEST ] nvme-cli

### ISSUE THREAD

**Issue by Samueru-sama** [Azathothas/Toolpacks#36]
I wanted to make the PR but I got stuck trying to compile it statically lol 

[instructions](https://github.com/linux-nvme/nvme-cli?tab=readme-ov-file#minimal-static-build-with-muon)

TL:DR `git clone repo && make static`

I tried building on ubuntu 20.04 and I get some errors about that I can't statically link getaddrinfo (glibc issue).

I then tried on alpine and I get this error: 

```
ninja -C .build
ninja: Entering directory `.build'
[1024/1130] Compiling C object nvme.p/nvme-print.c.o
FAILED: nvme.p/nvme-print.c.o 
cc -Invme.p -I. -I.. -Iccan -I../ccan -Isubprojects/libnvme/src -I../subprojects/libnvme/src -Isubprojects/json-c-0.17 -I../subprojects/json-c-0.17 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -fomit-frame-pointer -D_GNU_SOURCE -include config.h -pthread -MD -MQ nvme.p/nvme-print.c.o -MF nvme.p/nvme-print.c.o.d -o nvme.p/nvme-print.c.o -c ../nvme-print.c
../nvme-print.c: In function 'is_temperature_fahrenheit':
../nvme-print.c:792:19: error: 'LC_MEASUREMENT' undeclared (first use in this function)
  792 |         setlocale(LC_MEASUREMENT, "");
      |                   ^~~~~~~~~~~~~~
../nvme-print.c:792:19: note: each undeclared identifier is reported only once for each function it appears in
[1045/1130] Compiling C object nvme.p/nvme.c.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:61: static] Error 1
```

Note that the name of the binary is **nvme** instead of nvme-cli

**Comment by Azathothas** [comment]
Added:  https://github.com/Azathothas/Toolpacks/commit/ee4721e0e4cc74e56ab51bed72fbee09705a5aba
Please test & let me know if it works as expected:
[+] https://bin.ajam.dev/x86_64_Linux/nvme
```bash
curl -qfsSL "https://bin.ajam.dev/$(uname -m)/nvme" -o "./nvme" && chmod  +x "./nvme"
"./nvme" --help
```

**Comment by Samueru-sama** [comment]
> Added: [ee4721e](https://github.com/Azathothas/Toolpacks/commit/ee4721e0e4cc74e56ab51bed72fbee09705a5aba) Please test & let me know if it works as expected: [+] https://bin.ajam.dev/x86_64_Linux/nvme
> 
> ```shell
> curl -qfsSL "https://bin.ajam.dev/$(uname -m)/nvme" -o "./nvme" && chmod  +x "./nvme"
> "./nvme" --help
> ```
It works, thank you!

![image](https://github.com/user-attachments/assets/61b8f851-027e-4029-9496-6e8869d3bd7d)
